name: Build Unix
on: [push]
jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - name: Checkout code from Git repository
      uses: actions/checkout@v1
    - name: Building project
      run: make
    - name: Running tests
      run: make test
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: release-${{ matrix.os }}
        path: ./bin
    - uses: toolmantim/release-drafter@v5.2.0
      if: ${GITHUB_REF} == master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
